name: TFSec Analysis

on:
  push:
    branches:
      - main

jobs:
  tfsec_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: Varonis/
      
    - name: Install tfsec
      run: |
        curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?-linux-amd64")" -o /tmp/tfsec
        sudo install -m 755 /tmp/tfsec /usr/local/bin/tfsec
        
    - name: Run tfsec
      run: tfsec Varonis/

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        
    - name: Run Trivy vulnerability scan
      run: |
        trivy --exit-code 1 --severity HIGH --no-progress Varonis/
