name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install AWS CLI
      run: |
        pip install awscli
        
    - name: Deploy EC2 Instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0d118c6e63bcb554e \
          --instance-type t2.micro \
          --subnet-id subnet-0cc48c7a2cb8c1695 \
          --security-group-ids sg-0f71b39afa55809ea \
          --key-name your-key-pair-name
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET }}
